name: AutoStage Preview Deployment

on:
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  build:
    name: Build Docker Image
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Build Docker image
        run: docker build -t autostage-app .  

        

      - name: Deploy to EC2
        uses: appleboy/ssh-action@v1.2.2
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ubuntu
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            PR_NUMBER=${{ github.event.pull_request.number }}
            PORT=$((8080 + PR_NUMBER))
            CONTAINER_NAME="autostage-pr-${PR_NUMBER}"

            echo "Deploying PR #${PR_NUMBER}"
            echo "Container: ${CONTAINER_NAME}"
            echo "Port: ${PORT}"

            cd ~/Autostage_CI_CD
            git pull origin test-preview

            docker build -t ${CONTAINER_NAME} .

            docker rm -f ${CONTAINER_NAME} || true

            docker run -d \
              -p ${PORT}:80 \
              --name ${CONTAINER_NAME} \
              ${CONTAINER_NAME}

            docker ps