name: AutoStage Preview Deployment

on:
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  build:
    name: Build Docker Image
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Build Docker image
        run: docker build -t autostage-app .  

        

      - name: Deploy to EC2
        uses: appleboy/ssh-action@v1.2.2
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ubuntu
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            cd ~/Autostage_CI_CD
            git pull origin test-preview
            docker build -t autostage-pr-1 .
            docker rm -f autostage-pr-1 || true
            docker run -d -p 8081:80 --name autostage-pr-1 autostage-pr-1
            docker ps